server:
  port: 8082

spring:
  application:
    name: catalog-event-service
  datasource:
    url: jdbc:mysql://localhost:3307/catalog_event
    username: root
    password: insecure
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
